name: Build and Deploy

on:
  push:
    branches:
      - feature/github_actions

# env:
#   applicationfolder: spring-boot-hello-world-example
#   AWS_REGION: ##region##
#   S3BUCKET: ##s3-bucket## 


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install rsync
      run: sudo apt-get update && sudo apt-get install -y rsync

    # - name: Setup SSH
    #   run: |
    #     mkdir -p ~/.ssh
    #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
    #     chmod 600 ~/.ssh/id_rsa
    #     ssh-keyscan -H ${{ secrets.SSH_HOST_IP }} >> ~/.ssh/known_hosts

    - name: Deploy with rsync
      uses: burnett01/rsync-deployments@7.1.0
      with:
        switches: -avzr --delete
        path: ./
        remote_path: ${{ secrets.APP_LOCATION }}
        remote_host: ${{ secrets.SSH_HOST_IP }}
        remote_user: ${{ secrets.SSS_HOST_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
