name: Build and Deploy

on:
  push:
    branches:
      - feature/github_actions

# env:
#   applicationfolder: spring-boot-hello-world-example
#   AWS_REGION: ##region##
#   S3BUCKET: ##s3-bucket## 


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install rsync
      run: sudo apt-get update && sudo apt-get install -y rsync

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST_IP }} >> ~/.ssh/known_hosts

    - name: Stop application
      run: |
        ssh ${{ secrets.SSH_HOST_USER }}@${{ secrets.SSH_HOST_IP }} \
           cd ${{ secrets.APP_LOCATION }} && \
           bash scripts/stop_application.sh" || true

    - name: Deploy with rsync
      run: |
        rsync -avz --exclude '.git' --exclude '.github' --exclude 'venv' --exclude '__pycache__' --exclude '*.pyc' --exclude '.env' ./ ${{ secrets.SSH_HOST_USER }}@${{ secrets.SSH_HOST_IP }}:${{ secrets.APP_LOCATION }}

    - name: After Install 
      run: |
        ssh ${{ secrets.SSH_HOST_USER }}@${{ secrets.SSH_HOST_IP }} \
           cd ${{ secrets.APP_LOCATION }} && \
           bash scripts/after_install.sh" || true

    - name: Start Application 
      run: |
        ssh ${{ secrets.SSH_HOST_USER }}@${{ secrets.SSH_HOST_IP }} \
           cd ${{ secrets.APP_LOCATION }} && \
           bash scripts/start_application.sh" || true
